version: '3'

services:
    node:
      image: node:latest
      environment:
        - TZ=Asia/Tokyo
      ports:
        - "8080:8080"
      volumes:
        - ./:/usr/src
      working_dir: /usr/src
      tty: true